name: sarvey-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - setuptools
  - cython
  - pyproj
  - h5py
  - numpy
  - isce2
  - scipy
  - pip
  - gcc_linux-64
  - matplotlib
  - overpy
  - numba
  - mintpy
  - git
  - shapely
  - geopandas
  - gstools
  - pydantic=1.10.*
  - json5
  - pillow

  # Setup / test / lint / docs / deploy
  - tox
  - pytest
  - pytest-cov
  - urlchecker
  - flake8
  - pycodestyle
  - pydocstyle
  - pylint
  - sphinx>=4.1.1
  - sphinx-argparse
  - sphinx-autodoc-typehints
  - sphinxcontrib-jquery
  - sphinx_rtd_theme
  - twine

  - pip:
      - kamui[extra]
      - cmcrameri
      - pytest-reporter-html1
